[ai_model]
model_path = "/home/zaigiaz/third_party/ai_models/Qwen/Qwen3-4B-Instruct-2507-Q8_0.gguf"

[crawler]
# for testing purposes
crawl_path = "/home/zaigiaz/Programming/Cruft-Crawler-2/src/test_directory/askd/"
