* OVERVIEW
I need to finish these todos over spring break

* TODOS
** CRAWLER
TODO: fallback logic if entire program crashes (or if files already in DB)
TODO: cleanup crate names and prune redundancies
TODO: think about how this should work: fields, etc.
TODO: model prompt message string
TODO: implement voting or consensus logic?
TODO: (integration testing) for get_file_hash()
TODO: (integration testing) for visit_dir()
TODO: log errors, and add match or .expect() for various functions

** DB MANAGER
TODO: https://sledoview.greq.me/ download and use this for viewing database (for debugging)
TODO: match results for db operations
TODO: crawler <-> DB fallback logic
TODO: actor shutdown?
TODO: inotify integration
TODO: add fallback state 
TODO: use .back() to get iter for last element, then compare with write-ahead log
TODO: integration and unit testing

** INOTIFY
TODO: basic initiation
TODO: basic actor setup
TODO: watch-list management
TODO: write logic to edit DB if File in DB is changed

** Cgroups
TODO: learn and see how it interacts with steady-state process
TODO: could be our silver bullet

** TUI
TODO: list operations, write code to actually delete files given a path.
TODO: color coding for nice output?

** AI
TODO: Prompt Message (Although we would get this from Crawler, and would be stored in DB)
TODO: Create Slides, Notes, for presentations on Llama.cpp and Local LLM inference
TODO: Write Mockup of all the models we tried and the strengths/weaknesses of different approaches.
