* OVERVIEW
I need to finish these todos over spring break

TODO: user interface to correctly save to correct db location and other stuff
NOTE: some type of system variable?

* TODOS
** CRAWLER
TODO: fallback logic if entire program crashes (or if files already in DB)
TODO: cleanup crate names and prune redundancies
TODO: model prompt message string
TODO: implement voting or consensus logic?
TODO: (integration testing) for get_file_hash()
TODO: (integration testing) for visit_dir()
TODO: (integration testing) for rx and channel testing
TODO: log errors, and add match or .expect() for various functions

** DB MANAGER
TODO: think about structure of the Crawler iterator and how interact with WAL and DB
TODO: https://sledoview.greq.me/ download and use this for viewing database (for debugging)
TODO: implement tuple macro for db batching and shizz
TODO: match results for db operations
TODO: crawler <-> DB fallback logic
TODO: actor shutdown?
TODO: inotify integration
TODO: add fallback state 
TODO: use .back() to get iter for last element, then compare with write-ahead log
TODO: integration and unit testing

** INOTIFY
TODO: basic initiation
TODO: basic actor setup
TODO: watch-list management
TODO: write logic to edit DB if File in DB is changed

** TUI
TODO: list operations, write code to actually delete files given a path.
TODO: color coding for nice output?

** AI
TODO: Prompt Message (Although we would get this from Crawler, and would be stored in DB)
TODO: Create Slides, Notes, for presentations on Llama.cpp and Local LLM inference
TODO: Write Mockup of all the models we tried and the strengths/weaknesses of different approaches.

** Final Stuff
TODO: test running for multiple days/week
TODO: record demo video for presentation



*** old code
// this is a busy spin-loop, ignore for now
// async fn batch_or_timeout<A: SteadyActor>(actor: &mut A, crawler_rx: SteadyRx<FileMeta>) -> bool {
//     loop {
//         select! {
// 	    avail = actor.wait_avail(&mut crawler_rx, BATCH_SIZE) => {
//                 if avail {
// 		    return true;
//                 }
//             },
//             timeout = actor.wait_timeout(Duration::from_secs(5)) => {
//                 if timeout {
//                     return false;
//                 }
//             },
//         }
//     }
// }
